### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [BachToTheFuture/ProjectHexHax#10]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data  http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/SYC0KZ
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community

**Comment by BachToTheFuture** [comment]
Hello!
The datasets used in this project were from NASA and other research facilities, not our own, thus I don't think we're allowed to maintain these datasets.
Thank you so much for the offer!
